### ISSUE TITLE
Compile a folder of clothing icons

### ISSUE THREAD

**Issue by csabbah** [Wearther-A-Squad/interactive-proj-wearther#20]
## Description
* These icons should be **.png** annd will be used to represent the different weather temperatures 
* Icons should represent many weather conditions such as: **cold, hot, rainy, heavy winds and etc.**
* There should be a variety of icons and not just shirts representing all weathers, but, other types of clothing to represent all weather conditions as well

**Comment by tyler94flynn** [comment]
[flaticon](https://www.flaticon.com/search?word=shirt&type=icon) example
