### ISSUE TITLE
Create an object with all the major cities in a country

### ISSUE THREAD

**Issue by csabbah** [Wearther-A-Squad/interactive-proj-wearther#23]
## Description
* The amazon API allows us to search in a given region such as Canada or United states thus, we can create an object and then test the users selected city against that object. For example, var majorCities = [{US: [new york, chicago]}, {CA: [toronto, vancouver]}]
  
* From there, we can create a condition to return amazon listings in relevance to the users location.
* Example of condition: if (countryObject.includes(usersCity)) {url = 'api&region=CA'}

**Comment by tyler94flynn** [comment]
added list of canadian cities
