### ISSUE TITLE
Do not fetch for the data if the city returns null

### ISSUE THREAD

**Issue by csabbah** [Wearther-A-Squad/interactive-proj-wearther#25]
##Description
* Compare the city the user enters in the form with the citiesObject, if no city appears, then do not allow to submit
* OR, execute another fetch to see if any results return? (Not the most effective method)

**Comment by tyler94flynn** [comment]
lmaooo
![image](https://user-images.githubusercontent.com/98372617/161998363-b63e8738-e560-487d-8599-edc660c63cbd.png)
